// src/utils/memoryStyles.js
export const memoryStyles = {
    vintage: {
    label: "Vintage",
    backgroundColor: "#f5f0e1",
    fontFamily: "'Courier New', monospace",
    fontSize: "16px",
    color: "#3e2f1c",
    backgroundImage: "url('/backgrounds/vintage.png')", // transparent PNG
    backgroundSize: "cover",
    border: "8px solid #d4b483",
    borderRadius: "12px"
  },
  retro: {
    label: "Retro",
    backgroundColor: "#fff8dc",
    fontFamily: "'Roboto Slab', serif",
    fontSize: "16px",
    color: "#4b3832",
    backgroundImage: "url('/backgrounds/retro-pattern.avif')",
    backgroundSize: "cover",
    border: "6px solid #c94c4c",
    borderRadius: "10px"
  },
  wedding: {
    label: "Wedding",
    backgroundImage: "url('/backgrounds/wedding-flowers.webp')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#3c0f1f",
    fontFamily: "'Dancing Script', cursive",
    fontSize: "1.25rem",
    frame: "url('/frames/vintage.png')"
  },
  family: {
    label: "Family",
    backgroundImage: "url('/backgrounds/old-photo-collage.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#2f2419",
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.05rem",
    frame: "/frames/wooden-frame.png",
  },
  birthday: {
    label: "Birthday",
    backgroundImage: "url('/backgrounds/vintage-confetti.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#4b2e00",
    fontFamily: "'Comic Neue', cursive",
    fontSize: "1.1rem",
    frame: "/frames/balloon-frame.png",
  },
  vacation: {
    label: "Vacation",
    backgroundImage: "url('/backgrounds/retro-postcards.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#08323b",
    fontFamily: "'Roboto', sans-serif",
    fontSize: "1.05rem",
    frame: "/frames/postcard-frame.png",
  },
  graduation: {
    label: "Graduation",
    backgroundImage: "url('/backgrounds/aged-parchment.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#2b1652",
    fontFamily: "'Georgia', serif",
    fontSize: "1.15rem",
    frame: "/frames/scroll-frame.png",
  },
  anniversary: {
    label: "Anniversary",
    backgroundImage: "url('/backgrounds/vintage-roses.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#4a0f59",
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.2rem",
    frame: "/frames/gold-floral-frame.png",
  },
  christmas: {
    label: "Christmas",
    backgroundImage: "url('/backgrounds/vintage-christmas.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#3b1f10",
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.05rem",
    frame: "/frames/holly-frame.png",
  },
  travel: {
    label: "Travel",
    backgroundImage: "url('/backgrounds/retro-world-map.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#2c3a3a",
    fontFamily: "'Merriweather', serif",
    fontSize: "1.05rem",
    frame: "/frames/compass-map.png",
  },
  baby: {
    label: "Baby",
    backgroundImage: "url('/backgrounds/baby-pastel.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#4b3c3c",
    fontFamily: "'Kalam', cursive",
    fontSize: "1.05rem",
    frame: "/frames/baby-frame.png",
  },
  polaroid: {
    label: "Polaroid",
    backgroundImage: "url('/backgrounds/polaroid-stack.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#222",
    fontFamily: "'Arial', sans-serif",
    fontSize: "1rem",
    frame: "/frames/postcard-frame.png",
  },
  autumn: {
    label: "Autumn",
    backgroundImage: "url('/backgrounds/autumn-leaves.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#4a2b0f",
    fontFamily: "'Georgia', serif",
    fontSize: "1.05rem",
    frame: "/frames/leaf-frame.png",
  },
  seaside: {
    label: "Seaside",
    backgroundImage: "url('/backgrounds/vintage-beach.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#1f3a3a",
    fontFamily: "'Roboto', sans-serif",
    fontSize: "1.05rem",
    frame: "/frames/seashell-frame.png",
  },
  music: {
    label: "Music",
    backgroundImage: "url('/backgrounds/music-notes.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#2b1f2b",
    fontFamily: "'Playfair Display', serif",
    fontSize: "1.1rem",
    frame: "/frames/record-frame.png",
  },
  parchment: {
    label: "Parchment",
    backgroundImage: "url('/backgrounds/aged-parchment.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333",
    fontFamily: "'Times New Roman', serif",
    fontSize: "1rem",
    frame: "/frames/scroll-frame.png",
  },
  default: {
    label: "Default",
    backgroundImage: "url('/backgrounds/aged-paper.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Arial', sans-serif",
    fontSize: "1rem",
    frame: null,
  },
};
