// src/utils/styles.js
export const memoryStyles = {
  antiqueOldPaper: {
    label: "Antique Old Paper",
    backgroundImage: "url('/backgrounds/vintage.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  autumnLeaves: {
    label: "Autumn Leaves",
    backgroundImage: "url('/backgrounds/autumn-leaves.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  babyPastel: {
    label: "Baby Pastel",
    backgroundImage: "url('/backgrounds/baby-pastel.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  beigeGradient: {
    label: "Beige Gradient",
    backgroundImage: "url('/backgrounds/beige-gradient.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  cartoonSky: {
    label: "Cartoon Sky",
    backgroundImage: "url('/backgrounds/cartoon-sky.jpeg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  cherryBlossom: {
    label: "Cherry Blossom",
    backgroundImage: "url('/backgrounds/cherry-blossom.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  chineseLandscape: {
    label: "Chinese Landscape",
    backgroundImage: "url('/backgrounds/chinese-landscape.jpeg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  clouds: {
    label: "Clouds",
    backgroundImage: "url('/backgrounds/clouds.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  cosmos: {
    label: "Cosmos",
    backgroundImage: "url('/backgrounds/cosmos.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  deepSpace: {
    label: "Deep Space",
    backgroundImage: "url('/backgrounds/deep_space.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  digitalMatrix: {
    label: "Digital Matrix",
    backgroundImage: "url('/backgrounds/digital_matrix.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  elegantInk: {
    label: "Elegant Ink",
    backgroundImage: "url('/backgrounds/elegant-ink.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  floralWedding: {
    label: "Floral Wedding",
    backgroundImage: "url('/backgrounds/floral-wedding.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  flowers: {
    label: "Flowers",
    backgroundImage: "url('/backgrounds/flowers.png')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  forestSnow: {
    label: "Forest Snow",
    backgroundImage: "url('/backgrounds/forest-snow.webp')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  galaxy: {
    label: "Galaxy",
    backgroundImage: "url('/backgrounds/galaxy.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  graduatingTime: {
    label: "Graduating Time",
    backgroundImage: "url('/backgrounds/graduating-time.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  graduation: {
    label: "Graduation",
    backgroundImage: "url('/backgrounds/graduation.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  greenFrame: {
    label: "Green Frame",
    backgroundImage: "url('/backgrounds/green-frame.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  musicFrame: {
    label: "Music Frame",
    backgroundImage: "url('/backgrounds/music-frame.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  pastel: {
    label: "Pastel",
    backgroundImage: "url('/backgrounds/pastel.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  postcard: {
    label: "Postcard",
    backgroundImage: "url('/backgrounds/postcard.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  retroFlower: {
    label: "Retro Flower",
    backgroundImage: "url('/backgrounds/retro-flower.jpeg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  retroPattern: {
    label: "Retro Pattern",
    backgroundImage: "url('/backgrounds/retro-pattern.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  retroVaporwave: {
    label: "Retro Vaporwave",
    backgroundImage: "url('/backgrounds/retro_vaporwave.webp')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  retroWorldMap: {
    label: "Retro World Map",
    backgroundImage: "url('/backgrounds/retro-world-map.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  sky: {
    label: "Sky",
    backgroundImage: "url('/backgrounds/sky.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  space: {
    label: "Space",
    backgroundImage: "url('/backgrounds/space.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  springForest: {
    label: "Spring Forest",
    backgroundImage: "url('/backgrounds/spring-forest.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  vintageChristmas: {
    label: "Vintage Christmas",
    backgroundImage: "url('/backgrounds/vintage-christmas.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  vintageConfetti: {
    label: "Vintage Confetti",
    backgroundImage: "url('/backgrounds/vintage-confetti.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },

  time: {
    label: "Time",
    backgroundImage: "url('/backgrounds/time.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  vintage: {
    label: "Vintage",
    backgroundImage: "url('/backgrounds/vintage-paper.webp')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  watercolorGalaxy: {
    label: "Watercolor Galaxy",
    backgroundImage: "url('/backgrounds/watercolor_galaxy.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  watercolorFlower: {
    label: "Watercolor Flower",
    backgroundImage: "url('/backgrounds/watercolor-flower.jpeg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  weddingFlowers: {
    label: "Wedding Flowers",
    backgroundImage: "url('/backgrounds/wedding-flowers.webp')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  wedding: {
    label: "Wedding",
    backgroundImage: "url('/backgrounds/wedding.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  yellowVintageFlower: {
    label: "Yellow Vintage Flower",
    backgroundImage: "url('/backgrounds/yellow-vintage-flower.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  yellow: {
    label: "Yellow",
    backgroundImage: "url('/backgrounds/yellow.avif')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
  default: {
    label: "Default",
    backgroundImage: "url('/backgrounds/antique-old-paper.jpg')",
    backgroundSize: "cover",
    backgroundPosition: "center",
    color: "#333333",
    fontFamily: "'Georgia', serif",
    fontSize: "1rem",
  },
};